### PR TITLE
Feature/event name mapping

### PR DESCRIPTION
**Pull request by amiceli**
It adds an option `eventMapping` like eventToActionTransformer who allow to map event name from socket io event data.

An example : 

~~~js
// a socket io event example
{ name : 'event', data : { task : 'synchronize', progress : 90 } }
~~~

~~~js
const options = {
    eventMapping : (eventName, args) => {
        const data = args[0]

        return data.task
    }
}

Vue.use(VueSocketIOExt, socket, options);
~~~

And in vue component : 

~~~js
export default {
    sockets : {
        synchronize () {
            console.log ('progress received')
        }
    }
}
~~~

You're welcome if you have any feedbacks.

### CODE REVIEW

**Comment by amiceli** [comment]
Any news about merging ?
Thanks.

**Comment by probil** [comment]
@amiceli That's a good idea. Few nuances though: 
- there are linter issue (requires a simple code style fix)
- `dist/` shouldn't be committed

Will fix and merge tomorrow morning if you don't have time to deal with it

**Comment by amiceli** [comment]
@probil I will check it today.

**Comment by amiceli** [comment]
@probil Everything seems to be ok.

**Comment by probil** [comment]
@amiceli Could you apply this small suggestion regarding types?

**Comment by amiceli** [comment]
@probil done.

**Pull request merged**
