### PR TITLE
Add a description about how to emit an event using TypeScript

### PR DESCRIPTION
**Pull request by jnt0r**
As I started using this library along with TypeScript I struggled about how to emit an event. Finally, I found a solution (sadly not in the official documentation of this library). 

I wanted to contribute this so others don't face this struggle. Please give feedback if you know a better way to emit an event or I should edit my description.

### CODE REVIEW

**Comment by jnt0r** [comment]
Got it working without the `Vue.prototype thing`. I noticed that I need a vue-shim.d.ts file. Maybe this should be mentioned in the docs. At least a link/reference to the official Vue documentation about this definition file.

**Comment by probil** [comment]
@jnt0r I'm not that good at TS stuff. Could you provide PR with a link/reference you've mentioned?

**Comment by jnt0r** [comment]
I think my initial intention was wrong. that's why I closed this issue.
But overall the documentation to use the library with typescript is missing. I had to figure it out with StackOverflow and other Vue plugins. I would take a look at it in the next days and provide a PR.

**Comment by probil** [comment]
Thanks @jnt0r 
I'm looking forward to merge it

**Pull request closed without merging**
